import type { QuestMetric, QuestRule } from './types';

/**
 * The quest catalogue. Numbers are placeholders sized for a small community;
 * before launch they belong on the server, scaled to the player count, and
 * the rotation should be an editor's choice rather than a formula.
 */
export const QUESTS: QuestRule[] = [
  {
    id: 'compost-week',
    metric: 'compost',
    kind: 'reach',
    title: 'Compost week',
    blurb: 'Feed the soil the slow way. Every heap counts.',
    howTo: 'Play Gather compost, let the heap mature overnight, then fertilise with it.',
    lesson:
      'Compost returns carbon to the soil and replaces synthetic nitrogen, which is made from natural gas and releases nitrous oxide when it is spread.',
    goal: 500,
    stretchGoal: 800,
    personal: 2,
    reward: { stars: 0.1, stretchStars: 0.2, carbonDelta: -1 },
  },
  {
    id: 'walk-the-farm',
    metric: 'steps',
    kind: 'reach',
    title: 'Walk the farm',
    blurb: 'A community step count. Every GPS-verified step on ALLI RUN counts.',
    howTo: 'Run or walk with ALLI RUN. Your credited steps go on the pile.',
    lesson: 'A walk instead of a drive is the simplest low-carbon choice there is, and it is the one this app is built on.',
    goal: 20_000_000,
    stretchGoal: 30_000_000,
    personal: 12_000,
    reward: { stars: 0.1, stretchStars: 0.2, carbonDelta: 0 },
  },
  {
    id: 'thriving-week',
    metric: 'thrivingNights',
    kind: 'reach',
    title: 'Thriving week',
    blurb: 'Nights the community kept every meter above the line.',
    howTo: 'Water, tap and fertilise so your trees are above every line at midnight.',
    lesson: 'A tree that is never stressed grows the most and stores the most carbon. Consistency beats rescue.',
    goal: 3_000,
    stretchGoal: 4_500,
    personal: 3,
    reward: { stars: 0.1, stretchStars: 0.2, carbonDelta: 0 },
  },
  {
    id: 'sun-tappers',
    metric: 'sunFills',
    kind: 'reach',
    title: 'Sun tappers',
    blurb: 'Sun meters filled across the community.',
    howTo: 'Tap your tree a hundred times a day. Every full meter counts.',
    lesson: 'Sunlight is the only energy input a farm gets for free. Everything else is pumped, trucked or burned.',
    goal: 4_000,
    stretchGoal: 6_000,
    personal: 4,
    reward: { stars: 0.08, stretchStars: 0.16, carbonDelta: 0 },
  },
  {
    id: 'mulch-before-the-heat',
    metric: 'mulch',
    kind: 'reach',
    title: 'Mulch before the heat',
    blurb: 'Trees mulched while the heatwave is on.',
    howTo: 'Play Mulch the roots on a tree in a heatwave or drought.',
    lesson: 'Bare soil in a heatwave loses water and carbon. A layer of straw keeps both in the ground.',
    months: [2, 3, 4],
    goal: 300,
    stretchGoal: 500,
    personal: 1,
    reward: { stars: 0.12, stretchStars: 0.24, carbonDelta: -1 },
  },
  {
    id: 'clear-skies',
    metric: 'noBurn',
    kind: 'reach',
    title: 'Clear skies',
    blurb: 'No-burn pledges taken in the burning season.',
    howTo: 'Play Haze control on a tree while the haze is on.',
    lesson: 'Residue burning is what turns the sky grey every dry season. Baling keeps the carbon on the farm and the PM2.5 out of the air.',
    months: [1, 2, 3],
    goal: 300,
    stretchGoal: 500,
    personal: 1,
    reward: { stars: 0.12, stretchStars: 0.24, carbonDelta: -1 },
  },
  {
    id: 'synthetic-free',
    metric: 'synthetic',
    kind: 'stayUnder',
    title: 'Synthetic-free week',
    blurb: 'Keep the community\'s synthetic fertiliser use under the cap. Zero from you shares the reward.',
    howTo: 'Fertilise with compost, or with stars on a premium tree. Do not buy synthetic this week.',
    lesson: 'Synthetic nitrogen is the single biggest source of a farm\'s emissions: gas to make it, nitrous oxide when it is spread.',
    goal: 200,
    stretchGoal: 100,
    personal: 0,
    reward: { stars: 0.1, stretchStars: 0.2, carbonDelta: -1 },
  },
];

export const METRIC_LABEL: Record<QuestMetric, string> = {
  compost: 'compost uses',
  mulch: 'trees mulched',
  noBurn: 'pledges taken',
  thrivingNights: 'thriving nights',
  sunFills: 'sun meters filled',
  steps: 'steps',
  synthetic: 'synthetic uses',
};
